### ISSUE TITLE
The numeric keypad cannot be typed

### ISSUE THREAD

**Issue by ltinerary** [24min/ip-input#4]
There `event.code`‘s value : 

- Numpad0
- Numpad1
- Numpad2
- Numpad3
- Numpad4
- Numpad5
- Numpad6
- Numpad7
- Numpad8
- Numpad9
- NumpadDecimal

Please support this code.✨

**Comment by 24min** [comment]
todo: event.key ?

**Comment by 24min** [comment]
从 event.code 改为event.key判断。
